import React from "react";
import { TextInput } from "react-native-paper";
import { TextInputProps } from "react-native-paper/lib/typescript/src/components/TextInput/TextInput";

type MoneyInputProps = Pick<
  TextInputProps,
  | "ref"
  | "label"
  | "style"
  | "allowFontScaling"
  | "numberOfLines"
  | "onLayout"
  | "testID"
  | "nativeID"
  | "maxFontSizeMultiplier"
  | "selectionColor"
  | "textBreakStrategy"
  | "accessible"
  | "accessibilityActions"
  | "accessibilityLabel"
  | "accessibilityRole"
  | "accessibilityState"
  | "accessibilityHint"
  | "accessibilityValue"
  | "onAccessibilityAction"
  | "accessibilityComponentType"
  | "accessibilityLiveRegion"
  | "importantForAccessibility"
  | "accessibilityElementsHidden"
  | "accessibilityTraits"
  | "accessibilityViewIsModal"
  | "onAccessibilityEscape"
  | "onAccessibilityTap"
  | "onMagicTap"
  | "accessibilityIgnoresInvertColors"
  | "pointerEvents"
  | "key"
  | "disabled"
  | "hitSlop"
  | "removeClippedSubviews"
  | "collapsable"
  | "needsOffscreenAlphaCompositing"
  | "renderToHardwareTextureAndroid"
  | "focusable"
  | "shouldRasterizeIOS"
  | "isTVSelectable"
  | "hasTVPreferredFocus"
  | "tvParallaxProperties"
  | "tvParallaxShiftDistanceX"
  | "tvParallaxShiftDistanceY"
  | "tvParallaxTiltAngle"
  | "tvParallaxMagnification"
  | "onStartShouldSetResponder"
  | "onMoveShouldSetResponder"
  | "onResponderEnd"
  | "onResponderGrant"
  | "onResponderReject"
  | "onResponderMove"
  | "onResponderRelease"
  | "onResponderStart"
  | "onResponderTerminationRequest"
  | "onResponderTerminate"
  | "onStartShouldSetResponderCapture"
  | "onMoveShouldSetResponderCapture"
  | "onTouchStart"
  | "onTouchMove"
  | "onTouchEnd"
  | "onTouchCancel"
  | "onTouchEndCapture"
  | "render"
  | "right"
  | "onBlur"
  | "onFocus"
  | "multiline"
  | "value"
  | "error"
  | "placeholder"
  | "textAlignVertical"
  | "onContentSizeChange"
  | "onScroll"
  | "scrollEnabled"
  | "autoCapitalize"
  | "autoCorrect"
  | "autoFocus"
  | "blurOnSubmit"
  | "caretHidden"
  | "contextMenuHidden"
  | "defaultValue"
  | "editable"
  | "maxLength"
  | "onChange"
  | "onChangeText"
  | "onEndEditing"
  | "onSelectionChange"
  | "onSubmitEditing"
  | "onKeyPress"
  | "placeholderTextColor"
  | "returnKeyType"
  | "secureTextEntry"
  | "selectTextOnFocus"
  | "selection"
  | "inputAccessoryViewID"
  | "clearButtonMode"
  | "clearTextOnFocus"
  | "dataDetectorTypes"
  | "enablesReturnKeyAutomatically"
  | "keyboardAppearance"
  | "passwordRules"
  | "rejectResponderTermination"
  | "selectionState"
  | "spellCheck"
  | "textContentType"
  | "autoCompleteType"
  | "importantForAutofill"
  | "disableFullscreenUI"
  | "inlineImageLeft"
  | "inlineImagePadding"
  | "returnKeyLabel"
  | "underlineColorAndroid"
  | "showSoftInputOnFocus"
  | "underlineColor"
  | "dense"
>;

export default function MoneyInput(props: MoneyInputProps) {
  return (
    <TextInput
      mode="outlined"
      keyboardType="numeric"
      left={<TextInput.Icon name="currency-usd" />}
      {...props}
    />
  );
}
